In [1]:
import numpy as np


In [2]:
l = [1,2,3,4]

In [3]:
ar = np.array(l)
ar

array([1, 2, 3, 4])

In [4]:
type(ar)

numpy.ndarray

In [5]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [6]:
np.asarray(l)

array([1, 2, 3, 4])

In [7]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [8]:
b = np.matrix(l)

In [9]:
b

matrix([[1, 2, 3, 4]])

In [10]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [11]:
a = np.array(l)

In [12]:
a

array([1, 2, 3, 4])

In [ ]:
## swallow copy 
c = a


np.int64(66)

In [16]:
c[0]

np.int64(66)

In [17]:
c[0]=1

In [18]:
c[0]

np.int64(1)

In [19]:
a[0]

np.int64(1)

In [22]:
## creating new copy on new location
d = np.copy(a)